

# to avoid duplicates, every time we reseed (rake db:seed )

Viewing.destroy_all
Client.destroy_all
House.destroy_all


# create 18-20 houses, beds max = 2, bath max = 2

house1 = House.create(bedrooms: 1, bathrooms: 1, yard: true, location: "Denver", address: "3350 Clarkson St.")
house2 = House.create(bedrooms: 1, bathrooms: 1, yard: false, location: "Denver", address: "940 University Blvd.")
house3 = House.create(bedrooms: 1, bathrooms: 1, yard: true, location: "Denver", address: "868 Fox St.")
house4 = House.create(bedrooms: 1, bathrooms: 1, yard: false, location: "Denver", address: "3738 Lafayette St.")
house4 = House.create(bedrooms: 1, bathrooms: 2, yard: true, location: "Denver", address: "3738 Hampden St.")
house4 = House.create(bedrooms: 1, bathrooms: 2, yard: false, location: "Denver", address: "8763 63rd St.")
house4 = House.create(bedrooms: 1, bathrooms: 2, yard: true, location: "Denver", address: "8623 Pena Blvd.")
house4 = House.create(bedrooms: 1, bathrooms: 2, yard: false, location: "Denver", address: "8762 Greensburr St.")
house17 = House.create(bedrooms: 2, bathrooms: 1, yard: true, location: "Denver", address: "3046 Lakeridge St.")
house18 = House.create(bedrooms: 2, bathrooms: 2, yard: true, location: "Denver", address: "1902 16th Ave.")
house19 = House.create(bedrooms: 2, bathrooms: 1, yard: false, location: "Denver", address: "2345 Walnut St.")
house19 = House.create(bedrooms: 2, bathrooms: 1, yard: false, location: "Denver", address: "1254 Chestnut Lane")
house12 = House.create(bedrooms: 2, bathrooms: 1, yard: true, location: "Denver", address: "2823 Walnut St.")
house12 = House.create(bedrooms: 2, bathrooms: 2, yard: true, location: "Denver", address: "6915 Martin Luther King Blvd.")
house12 = House.create(bedrooms: 2, bathrooms: 2, yard: false, location: "Denver", address: "9847 Hadley Blvd.")
house12 = House.create(bedrooms: 2, bathrooms: 2, yard: true, location: "Denver", address: "5324 Hadley St.")
house12 = House.create(bedrooms: 2, bathrooms: 2, yard: false, location: "Denver", address: "6243 Hadley Blvd.")
house12 = House.create(bedrooms: 2, bathrooms: 2, yard: true, location: "Denver", address: "1236 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "4561 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "4509 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "8293 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "2834 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "2734 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "3249 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "3452 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "8762 Hadley Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Denver", address: "4905 Hadley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 1, yard: true, location: "Denver", address: "7832 Hadley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 1, yard: true, location: "Denver", address: "9853 Hadley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 1, yard: true, location: "Denver", address: "2938 Hadley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 1, yard: true, location: "Denver", address: "2783 Hadley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 1, yard: true, location: "Denver", address: "7623 Hadley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 1, yard: true, location: "Denver", address: "9458 Hadley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 1, yard: true, location: "Denver", address: "3249 Hadley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 1, yard: true, location: "Denver", address: "8372 Hadley Blvd.")

house5 = House.create(bedrooms: 1, bathrooms: 1, yard: true, location: "Boulder", address: "3375 14th St.")
house5 = House.create(bedrooms: 1, bathrooms: 1, yard: true, location: "Boulder", address: "6549 18th St.")
house6 = House.create(bedrooms: 1, bathrooms: 1, yard: false, location: "Boulder", address: "3040 10th St.")
house7 = House.create(bedrooms: 1, bathrooms: 2, yard: true, location: "Boulder", address: "3875 Cloverleaf Dr.")
house7 = House.create(bedrooms: 1, bathrooms: 2, yard: true, location: "Boulder", address: "265 Moonlight Dr.")
house8 = House.create(bedrooms: 1, bathrooms: 2, yard: true, location: "Boulder", address: "932 Arapahoe Ave.")
house12 = House.create(bedrooms: 2, bathrooms: 2, yard: true, location: "Boulder", address: "3143 Fern St.")
house20 = House.create(bedrooms: 2, bathrooms: 1, yard: true, location: "Boulder", address: "4357 Hampton Pl.")
house21 = House.create(bedrooms: 2, bathrooms: 1, yard: false, location: "Boulder", address: "5007 Coventry Ct.")
house21 = House.create(bedrooms: 2, bathrooms: 1, yard: false, location: "Boulder", address: "1347 Sterling Pl.")
house22 = House.create(bedrooms: 2, bathrooms: 2, yard: true, location: "Boulder", address: "930 Grant Pl.")
house12 = House.create(bedrooms: 1, bathrooms: 2, yard: false, location: "Boulder", address: "1810 Hillside Rd.")
house12 = House.create(bedrooms: 2, bathrooms: 2, yard: true, location: "Boulder", address: "1111 Utica Blvd.")
house12 = House.create(bedrooms: 2, bathrooms: 2, yard: true, location: "Boulder", address: "5500 Darling Rd.")
house12 = House.create(bedrooms: 1, bathrooms: 2, yard: true, location: "Boulder", address: "1910 Builmer St.")
house12 = House.create(bedrooms: 1, bathrooms: 2, yard: false, location: "Boulder", address: "9110 Deal St.")
house12 = House.create(bedrooms: 1, bathrooms: 2, yard: true, location: "Boulder", address: "8910 Drew Rd.")
house12 = House.create(bedrooms: 3, bathrooms: 2, yard: true, location: "Boulder", address: "8899 Albert St.")
house12 = House.create(bedrooms: 3, bathrooms: 2, yard: false, location: "Boulder", address: "9081 Middleton Dr.")
house12 = House.create(bedrooms: 3, bathrooms: 2, yard: true, location: "Boulder", address: "8901 Culpeper Rd.")
house12 = House.create(bedrooms: 3, bathrooms: 3, yard: true, location: "Boulder", address: "5109 Elia Blvd.")
house12 = House.create(bedrooms: 3, bathrooms: 3, yard: false, location: "Boulder", address: "1209 Thurloe St.")
house12 = House.create(bedrooms: 3, bathrooms: 3, yard: false, location: "Boulder", address: "3049 Allington Dr.")
house12 = House.create(bedrooms: 3, bathrooms: 3, yard: true, location: "Boulder", address: "1928 Doric Rd.")
house12 = House.create(bedrooms: 4, bathrooms: 2, yard: true, location: "Boulder", address: "1923 Alpha St.")
house12 = House.create(bedrooms: 4, bathrooms: 2, yard: true, location: "Boulder", address: "1266 Oceana Dr.")
house12 = House.create(bedrooms: 4, bathrooms: 2, yard: false, location: "Boulder", address: "6655 Temple Rd.")
house12 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Boulder", address: "5510 Station Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 3, yard: false, location: "Boulder", address: "4889 Parry St.")
house12 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Boulder", address: "2222 Bicknell Rd.")
house12 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Boulder", address: "9889 Robsart Dr.")
house12 = House.create(bedrooms: 4, bathrooms: 3, yard: false, location: "Boulder", address: "2342 Penley Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 3, yard: false, location: "Boulder", address: "2599 Curnock Rd.")
house12 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Boulder", address: "7768 Littlebury St.")
house12 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Boulder", address: "4132 Arthur Blvd.")
house12 = House.create(bedrooms: 4, bathrooms: 4, yard: true, location: "Boulder", address: "4536 Rawson Rd.")
house12 = House.create(bedrooms: 4, bathrooms: 4, yard: false, location: "Boulder", address: "3987 Shavers Ln.")
house12 = House.create(bedrooms: 4, bathrooms: 4, yard: false, location: "Boulder", address: "4298 Romer Rd.")
house12 = House.create(bedrooms: 4, bathrooms: 4, yard: false, location: "Boulder", address: "7512 Ashby St.")
house12 = House.create(bedrooms: 4, bathrooms: 4, yard: true, location: "Boulder", address: "9083 Bethwin Rd.")
house12 = House.create(bedrooms: 4, bathrooms: 4, yard: true, location: "Boulder", address: "7845 Bethany Ln.")


house9 = House.create(bedrooms: 1, bathrooms: 1, yard: true, location: "Littleton", address: "6220 Windermere St.")
house10 = House.create(bedrooms: 1, bathrooms: 1, yard: true, location: "Littleton", address: "2418 Bradbury Ave.")
house10 = House.create(bedrooms: 1, bathrooms: 1, yard: true, location: "Littleton", address: "876 Stary Night Ave.")
house11 = House.create(bedrooms: 1, bathrooms: 1, yard: false, location: "Littleton", address: "805 Peakview Circle")
house12 = House.create(bedrooms: 1, bathrooms: 2, yard: false, location: "Littleton", address: "329 Jamison Circle")
house12 = House.create(bedrooms: 1, bathrooms: 2, yard: false, location: "Littleton", address: "549 Jackson St.")
house13 = House.create(bedrooms: 1, bathrooms: 2, yard: true, location: "Littleton", address: "885 Briarwood Dr.")
house14 = House.create(bedrooms: 2, bathrooms: 1, yard: false, location: "Littleton", address: "1507 Cottonwood Ln")
house15 = House.create(bedrooms: 2, bathrooms: 1, yard: true, location: "Littleton", address: "5307 Cody St.")
house16 = House.create(bedrooms: 3, bathrooms: 1, yard: true, location: "Littleton", address: "5425 Lowell Blvd.")
house17 = House.create(bedrooms: 3, bathrooms: 2, yard: false, location: "Littleton", address: "8138 Stonybridge Circle")
house16 = House.create(bedrooms: 3, bathrooms: 2, yard: true, location: "Littleton", address: "8768 Emerald Ln")
house16 = House.create(bedrooms: 3, bathrooms: 2, yard: true, location: "Littleton", address: "2342 Hampden Circle")
house16 = House.create(bedrooms: 3, bathrooms: 2, yard: false, location: "Littleton", address: "2344 Highfield Dr.")
house16 = House.create(bedrooms: 3, bathrooms: 2, yard: true, location: "Littleton", address: "4643 Abbey Circle")
house16 = House.create(bedrooms: 3, bathrooms: 2, yard: true, location: "Littleton", address: "2446 Glenn St.")
house16 = House.create(bedrooms: 3, bathrooms: 3, yard: false, location: "Littleton", address: "5743 Main Circle")
house16 = House.create(bedrooms: 3, bathrooms: 3, yard: true, location: "Littleton", address: "1436 Nimitz St.")
house16 = House.create(bedrooms: 3, bathrooms: 3, yard: false, location: "Littleton", address: "4522 Dupont St.")
house16 = House.create(bedrooms: 3, bathrooms: 3, yard: true, location: "Littleton", address: "1463 Church St.")
house16 = House.create(bedrooms: 4, bathrooms: 2, yard: true, location: "Littleton", address: "4563 Lincoln St.")
house16 = House.create(bedrooms: 4, bathrooms: 2, yard: false, location: "Littleton", address: "2345 High St.")
house16 = House.create(bedrooms: 4, bathrooms: 2, yard: true, location: "Littleton", address: "1342 Barton St.")
house16 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Littleton", address: "4632 Broad St.")
house16 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Littleton", address: "1453 4th St.")
house16 = House.create(bedrooms: 4, bathrooms: 3, yard: false, location: "Littleton", address: "4351 Whitehurst St.")
house16 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Littleton", address: "7812 Kinsbury Dr.")
house16 = House.create(bedrooms: 4, bathrooms: 3, yard: true, location: "Littleton", address: "8807 Blue Ridge Dr.")
house16 = House.create(bedrooms: 4, bathrooms: 4, yard: false, location: "Littleton", address: "7657 Ranch Dr.")
house16 = House.create(bedrooms: 4, bathrooms: 4, yard: true, location: "Littleton", address: "9870 Center Dr.")
house16 = House.create(bedrooms: 4, bathrooms: 4, yard: false, location: "Littleton", address: "1341 River Dr.")
house16 = House.create(bedrooms: 4, bathrooms: 4, yard: true, location: "Littleton", address: "3456 State Dr.")
house16 = House.create(bedrooms: 4, bathrooms: 4, yard: true, location: "Littleton", address: "1257 Elm Dr.")
